#!/usr/bin/env python3
"""Generate docs/skills/index.json and docs/skills/index.md from skill front matter.

The catalog shape mirrors projectbluefin/common's skill catalog so factory tooling
can consume either repo with the same reader. Run with --check in CI to fail when
the committed catalog is stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "docs" / "skills"
INDEX_JSON = SKILLS_DIR / "index.json"
INDEX_MD = SKILLS_DIR / "index.md"
SCHEMA_VERSION = "1.0"

REQUIRED = (
    "id",
    "name",
    "one_line_purpose",
    "entry_point",
    "category",
    "status",
    "tags",
    "description",
    "version",
    "last_updated",
)
CATEGORIES = ("ci-ops", "test-authoring", "meta")
STATUSES = ("active", "deprecated", "reserved")


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise SystemExit(f"{path}: missing YAML front matter")
    parts = text.split("---", 2)
    data = yaml.safe_load(parts[1])
    if not isinstance(data, dict):
        raise SystemExit(f"{path}: front matter is not a mapping")
    return data


def collect() -> list[dict]:
    skills: list[dict] = []
    errors: list[str] = []
    for path in sorted(SKILLS_DIR.rglob("SKILL.md")):
        fm = parse_frontmatter(path)
        rel = path.relative_to(ROOT).as_posix()
        missing = [k for k in REQUIRED if not fm.get(k)]
        if missing:
            errors.append(f"{rel}: front matter missing {', '.join(missing)}")
            continue
        if fm["category"] not in CATEGORIES:
            errors.append(f"{rel}: category '{fm['category']}' not in {CATEGORIES}")
        if fm["status"] not in STATUSES:
            errors.append(f"{rel}: status '{fm['status']}' not in {STATUSES}")
        if fm["entry_point"] != rel:
            errors.append(f"{rel}: entry_point '{fm['entry_point']}' does not match its own path")
        if fm["id"] != fm["name"]:
            errors.append(f"{rel}: id '{fm['id']}' does not match name '{fm['name']}'")
        entry = {
            "id": fm["id"],
            "name": fm["name"],
            "one_line_purpose": fm["one_line_purpose"],
            "entry_point": fm["entry_point"],
            "category": fm["category"],
            "status": fm["status"],
            "tags": list(fm["tags"]),
            "description": " ".join(str(fm["description"]).split()),
            "version": str(fm["version"]),
            "last_updated": str(fm["last_updated"]),
        }
        doc_type = (fm.get("metadata") or {}).get("type")
        if doc_type:
            entry["doc_type"] = doc_type
        skills.append(entry)
    if errors:
        print("\n".join(f"FAIL: {e}" for e in errors), file=sys.stderr)
        raise SystemExit(1)
    return sorted(skills, key=lambda s: s["id"])


def render_json(skills: list[dict], generated_at: str) -> str:
    payload = {
        "generated_at": generated_at,
        "schema_version": SCHEMA_VERSION,
        "skills": skills,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def render_md(skills: list[dict], generated_at: str) -> str:
    lines = [
        "---",
        "name: index",
        'version: "1.0"',
        f'last_updated: "{generated_at}"',
        "description: >-",
        "  Generated skill catalog for testsuite. Human-readable mirror of index.json.",
        "  The task router lives in docs/SKILL.md.",
        "metadata:",
        "  type: manifest",
        "  audience: agents",
        "  maturity: stable",
        "---",
        "",
        "# Skill catalog (generated)",
        "",
        "This file is a human-readable mirror of [`index.json`](index.json). Both are",
        "generated by `scripts/generate_skill_index.py` — do not hand-edit either file.",
        "",
        "Looking for the task router? See [`docs/SKILL.md`](../SKILL.md).",
        "",
        f"Generated: {generated_at} · schema {SCHEMA_VERSION} · {len(skills)} skills",
        "",
        "| id | category | status | one-line purpose |",
        "|---|---|---|---|",
    ]
    for s in skills:
        href = Path(s["entry_point"]).relative_to("docs/skills").as_posix()
        lines.append(f"| [{s['id']}]({href}) | {s['category']} | {s['status']} | {s['one_line_purpose']} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed catalog is stale")
    args = ap.parse_args()

    skills = collect()
    generated_at = date.today().isoformat()

    if args.check:
        if not INDEX_JSON.exists():
            print("FAIL: docs/skills/index.json is missing; run scripts/generate_skill_index.py")
            return 1
        current = json.loads(INDEX_JSON.read_text(encoding="utf-8"))
        if current.get("skills") != skills:
            print("FAIL: docs/skills/index.json is stale; run scripts/generate_skill_index.py")
            return 1
        expected_md = render_md(skills, current.get("generated_at", generated_at))
        if INDEX_MD.read_text(encoding="utf-8") != expected_md:
            print("FAIL: docs/skills/index.md is stale; run scripts/generate_skill_index.py")
            return 1
        print(f"Skill catalog is in sync ({len(skills)} skills).")
        return 0

    INDEX_JSON.write_text(render_json(skills, generated_at), encoding="utf-8")
    INDEX_MD.write_text(render_md(skills, generated_at), encoding="utf-8")
    print(f"Wrote {len(skills)} skills to docs/skills/index.json and docs/skills/index.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
