name: issue and PR lifecycle

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  lifecycle:
    uses: projectbluefin/actions/.github/workflows/lifecycle.yml@4d46a63f49ed0159e2f5958a2109cc936a50417e # main
    with:
      brand_name: "Testsuite"
    secrets: inherit
